# Generated by Django 2.2.2 on 2019-08-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Mobile', models.IntegerField()),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
            ],
        ),
    ]
